"""
Internal constants for Slowcat configuration
These are technical settings that users should not need to configure
"""

# === MLX & METAL OPTIMIZATION ===
MLX_METAL_MEMORY_LIMIT = "8GB"
MLX_METAL_BUFFER_SIZE = "1GB"
MLX_METAL_SINGLE_THREADED = True
METAL_SINGLE_THREADED = True
METAL_DEVICE_WRAPPER_TYPE = 1
METAL_DEBUG_ERROR_MODE = 0
MTL_SHADER_VALIDATION = 0
MTL_DEBUG_LAYER = 0

# === SHERPA-ONNX SPEECH RECOGNITION ===
SHERPA_CHUNK_MS = 250
SHERPA_THREADS = 8
SHERPA_MAX_PATHS = 4
SHERPA_RULE1_MIN_TRAILING_SILENCE = 1.5
SHERPA_RULE2_MIN_TRAILING_SILENCE = 2.5
SHERPA_RULE3_MIN_UTTERANCE_LENGTH = 500
SHERPA_ENABLE_PUNCTUATION = True
SHERPA_ENABLE_ACCURACY_ENHANCEMENT = False
SHERPA_ONLINE_STREAMING = True
SHERPA_ENDPOINT_DETECTION = True
SHERPA_PARTIAL_RESULTS = False
SHERPA_DECODING_METHOD = "greedy_search"
SHERPA_PROVIDER = "cpu"
SHERPA_ONNX_MODEL_DIR = "./models/kroko-asr-en"

# === SMART CONTEXT MANAGER ===
SC_ENFORCE_GREETING = True
SC_LOG_SESSIONS = True
SC_MEMORY_COOLDOWN_S = 30
SC_RECENT_MIN_EXCHANGES = 20
SC_RECENT_TRUNCATE_CHARS = 1300
SC_SCHEMA_MODE = "graph"
SC_SKIP_LEGACY_SCHEMA_INIT = True
SC_SUMMARY_EVERY_N = 40
SC_SUMMARY_LAST_TURNS = 20
SC_SUMMARY_USE_LLM = True
SC_TRACE_SESSIONS = True
SC_UNIFIED_MEMORY = True
SC_USE_ABSTRACT_SUMMARY = True

# === RESPONSE & PROCESSING ===
RESPONSETAP_MIN_STABLE_MS = 400
RESPONSETAP_COMMIT_DEBOUNCE_MS = 600
RESPONSE_FORMATTER_MODE = "off"
ROUTER_THRESHOLD_LOW = 0.05

# === MEMORY & DATABASE ===
MEMORY_BACKEND = "surreal"
SURREAL_EMBED_TAPE = True
TAPE_MIN_USEFUL_WORDS = 3
TAPE_MIN_USEFUL_LEN = 15
FACTS_MAX_NONUSER = 6
INCLUDE_NAME_IN_FACTS = True
USE_SURREALDB = True
USE_CONTEXT_FIELD = True
USE_CROSS_ENCODER = True

# === FEATURE FLAGS (INTERNAL) ===
ENABLE_ASYNC_EXTRACTION = True
ENABLE_DTH = True
ENABLE_SMART_ROUTING = True
ENABLE_SPELLING_HINTS = True
ENABLE_GREETING_FALLBACK = False
USE_MINIMAL_PROMPTS = True

# === LOGGING & DEBUG ===
STT_VERBOSE = False
STT_LOG_INTERIM = False
STT_LOG_PUNCT = False
TTS_VERBOSE = False
TTS_LOG_SANITIZATION = False

# === MODEL OPTIMIZATION ===
ENABLE_SPECULATIVE = True
SPECULATIVE_DRAFT_MODEL = "qwen/qwen3-4b"
SPECULATIVE_MAX_DRAFT_TOKENS = 5
SPECULATIVE_MIN_DRAFT_TOKENS = 2
ALTERNATE_SUMMARIZER_MODEL = "dolphin3.0-llama3.2-3b"
SUMMARIZER_PROVIDER = "lmstudio"
SUMMARIZER_MODEL = "qwen/qwen3-4b"

# === OFFLINE MODE ===
HF_HUB_OFFLINE = True
TRANSFORMERS_OFFLINE = True

# === DSPY OPTIMIZATION (ADVANCED) ===
DSPY_OPTIMIZATION_ENABLED = False
DSPY_OPTIMIZATION_INTERVAL = 7200  # 2 hours
DSPY_OPTIMIZATION_START_HOUR = 2
DSPY_OPTIMIZATION_END_HOUR = 6
DSPY_MAX_MEMORY_MB = 2000

# === SURREALDB SERVER ===
SURREALDB_HOST = "127.0.0.1"
SURREALDB_PORT = 8000
SURREALDB_DATA_DIR = "data/surrealdb"

# === PATHS & FILES ===
MEMORY_FILE_PATH = "./data/tool_memory/memory.json"
ENABLED_LOCAL_TOOLS = "none"

# === REFLECTION SYSTEM ===
ENABLE_BACKGROUND_REFLECTIONS = True
ENABLE_LLM_REFLECTIONS = True
ENABLE_EMERGENT_TRACKING = True
EMERGENT_LOOKBACK_TURNS = 30
REFLECTION_LLM_MAX_TOKENS = 1000

# === SMART TURN MANAGEMENT ===
ENABLE_SMART_TURN_MANAGEMENT = False  # Disabled for simplicity

# === MISC TECHNICAL ===
DISABLE_ALL_TOOLS = False
ENABLE_THINKING = False